# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "pip"
      - "dependencies"
    groups:
      click-deps:
        applies-to: version-updates
        patterns: ["click*"]
      nornir-deps:
        applies-to: version-updates
        patterns: ["nornir*"]
      docs-deps:
        applies-to: version-updates
        patterns:
          - "mike"
          - "mkdocs*"
          - "myst-parser"
          - "sphinx*"
      lint-deps:
        applies-to: version-updates
        patterns:
          - "darglint"
          - "flake8*"
          - "pep8*"
          - "toml"
      test-deps:
        applies-to: version-updates
        patterns:
          - "coverage"
          - "mock"
          - "py"
          - "pytest*"
          - "testfixtures"
      build-deps:
        applies-to: version-updates
        patterns:
          - "nox"
          - "setuptools*"
          - "wheel"
      python-deps:
        applies-to: version-updates
        patterns: ["*"]
        exclude-patterns:
          - "click*"
          - "nornir*"
          - "mike"
          - "mkdocs*"
          - "myst-parser"
          - "sphinx*"
          - "darglint"
          - "flake8*"
          - "pep8*"
          - "toml"
          - "coverage"
          - "mock"
          - "py"
          - "pytest*"
          - "testfixtures"
          - "nox"
          - "setuptools*"
          - "wheel"
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github_actions"
      - "dependencies"
    groups:
      actions:
        applies-to: version-updates
        patterns: ["*"]
