#!/usr/bin/env bash
echo "######################################################################"
echo "# Creating CANU development environment in a container"
echo "######################################################################"

IMAGE="canu-devel"
REBUILD=${1:-"same"}

#
# Try to get an ssh key for CANU github
#
if [[ ${SSHKEYFILE:-"unset"} == "unset" ]];then
    read -er -p "Public GitHub Cray-HPE ssh key (full path): " SSHKEYFILE
fi
if [[ ! -f ${SSHKEYFILE} ]]; then
    echo "ERROR:  Key file ${SSHKEYFILE} does not exist."
    exit 1
fi


#
# Find a container platform (podman, docker, etc...)
#
for platform in podman docker;do
    if which ${platform} >/dev/null 2>&1;then
        PLATFORM=$(which ${platform})
        break
    fi
done

if [[ -z ${PLATFORM} ]];then
   echo "No container platform (podman, docker etc...) found.  Exiting..."
   exit 1
fi

if [[ $(basename "${PLATFORM}") == "podman" ]];then
    MOUNTOPTS="Z,U"
    [[ $(id -u) -ne 0 ]] && RUNOPTS="--user 0"
else
    MOUNTOPTS="rw"
fi


#
# Build an image if required
#
if [[ -z $(${PLATFORM} image ls -q ${IMAGE}) || ${REBUILD} == "rebuild" ]];then
    echo "# Building CANU image ${IMAGE}. This may take time to download and create."
    ${PLATFORM} build -t "${IMAGE}" -f Dockerfile.prod .
fi


set -x
#
# Start CANU container
#
echo "# Launching CANU container"
echo "#   CANU version $(cat ./canu/.version)"
echo "#   Read-Only GitHub ssh key located at /home/canu/key"
echo '#   Type "exit" or "Ctrl+D" to exit the container'
# shellcheck disable=SC2086
${PLATFORM} run ${RUNOPTS} -it --rm \
    -v "${SSHKEYFILE}":/home/canu/key:ro \
    -v "$(pwd)"/:/files:"${MOUNTOPTS}" \
    --name "${IMAGE}" \
    --hostname "${IMAGE}" \
    "${IMAGE}" \
    /bin/bash
