#!/usr/bin/env bash

IMAGE="canu-prod"
REBUILD=${1:-"same"}


#
# Find a container platform (podman, docker, etc...)
#
for platform in podman docker;do
    if which ${platform} >/dev/null 2>&1;then
        PLATFORM=$(which ${platform})
        break
    fi
done

if [[ -z ${PLATFORM} ]];then
   echo "No container platform (podman, docker etc...) found.  Exiting..."
   exit 1
fi

if [[ $(basename "${PLATFORM}") == "podman" ]];then
    MOUNTOPTS="Z,U"
    [[ $(id -u) -ne 0 ]] && RUNOPTS="--user 0"
else
    MOUNTOPTS="rw"
fi


#
# Build an image if required
#
if [[ -z $(${PLATFORM} image ls -q ${IMAGE}) || ${REBUILD} == "rebuild" ]];then
    echo "# Building CANU image ${IMAGE}. This may take time to download and create."
    ${PLATFORM} build -t "${IMAGE}" -f Dockerfile.prod .
fi


#
# Start CANU container
#
# shellcheck disable=SC2086
${PLATFORM} run ${RUNOPTS} -it --rm \
    -v "$(pwd)"/:/files:"${MOUNTOPTS}" \
    --name "${IMAGE}" \
    --hostname "${IMAGE}" \
    "${IMAGE}" \
    canu "${@}"
