#!/usr/bin/env bash

IMAGE="canu-prod"
REBUILD=${1:-"same"}

#
# Find a container platform (podman, docker, etc...)
#
for platform in podman docker;do
    which ${platform} >/dev/null 2>&1 
    if [[ $? == 0 ]];then
        PLATFORM=$(which ${platform})
        break
    fi
done

if [[ -z ${PLATFORM} ]];then
   echo "No container platform (podman, docker etc...) found.  Exiting..."
   exit 1
fi

if [[ $(basename ${PLATFORM}) == "podman" ]];then
    PLATFORM="${PLATFORM}"
    #RUNOPTS="--user 0"
    MOUNTOPTS="Z,U"
else
    MOUNTOPTS="rw"
fi

#
# Build an image if required
#
if [[ -z $(${PLATFORM} image ls -q ${IMAGE}) || ${REBUILD} == "rebuild" ]];then
    echo "# Building CANU image ${IMAGE}. This may take time to download and create."
    ${PLATFORM} build -t ${IMAGE} -f Dockerfile.prod .
fi



set -x
#
# Start CANU container
#
echo "# Launching CANU container"
echo "#   CANU version $(cat ./canu/.version)"
echo "#   Read-Only GitHub ssh key located at /home/canu/key"
echo '#   Type "exit" or "Ctrl+D" to exit the container'
${PLATFORM} run ${RUNOPTS} -it --rm \
    -v "${SSHKEYFILE}":/home/canu/key:ro \
    -v $(pwd)/:/files:${MOUNTOPTS} \
    --name ${IMAGE} \
    --hostname ${IMAGE} \
    ${IMAGE} \
    /bin/bash
