#!/usr/bin/env bash
# MIT License
#
# (C) Copyright [2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

IMAGE="canu-prod"
REBUILD=${1:-"same"}


#
# Find a container platform (podman, docker, etc...)
#
for platform in podman docker;do
    if which ${platform} >/dev/null 2>&1;then
        PLATFORM=$(which ${platform})
        break
    fi
done

if [[ -z ${PLATFORM} ]];then
   echo "No container platform (podman, docker etc...) found.  Exiting..."
   exit 1
fi

if [[ $(basename "${PLATFORM}") == "podman" ]];then
    MOUNTOPTS="Z,U"
    [[ $(id -u) -ne 0 ]] && RUNOPTS="--user 0"
else
    MOUNTOPTS="rw"
fi


#
# Build an image if required
#
if [[ -z $(${PLATFORM} image ls -q ${IMAGE}) || ${REBUILD} == "rebuild" ]];then
    echo "# Building CANU image ${IMAGE}. This may take time to download and create."
    ${PLATFORM} build -t "${IMAGE}" -f Dockerfile.prod .
fi


#
# Start CANU container
#
# shellcheck disable=SC2086
${PLATFORM} run ${RUNOPTS} -it --rm \
    -v "$(pwd)"/:/files:"${MOUNTOPTS}" \
    --name "${IMAGE}" \
    --hostname "${IMAGE}" \
    "${IMAGE}" \
    canu "${@}"
