---
  # Indicates the style of the configuration
  style: aoscx
  # if there is a delta, negate the parents and re-write the parents with children
  sectional_overwrite: []
  # if there is a delta, overwrite these parents instead of one of their children
  sectional_overwrite_no_negate: []
  # The default order value is 500, with a range between 1 - 999.
  # Commands with smaller order values float to the top in the order of execution.
  # Commands with larger order values float to the bottom in the order of execution.
  # Syntax Example:
  # - lineage:
  #   - startswith:
  #     - no route-map
  #   order: 600
  ordering:
    - lineage:
        - startswith: hostname
      order: 1
    - lineage:
        - startswith: bfd
      order: 2
    - lineage:
        - startswith: user
      order: 3
    - lineage:
        - startswith: vrf
      order: 5
    - lineage:
        - startswith: ssh
      order: 10
    - lineage:
        - startswith: ntp
      order: 15
    - lineage:
        - startswith: access-list
      order: 30
    - lineage:
        - startswith: vlan
      order: 50
    - lineage:
        - startswith: spanning-tree
      order: 100
    - lineage:
        - startswith: interface mgmt
      order: 120
    - lineage:
        - startswith: interface lag
      order: 160
    - lineage:
        - startswith: interface loopback
      order: 600
    - lineage:
        - startswith: interface vlan
      order: 700
    - lineage:
        - startswith: snmp-server
      order: 780
    - lineage:
        - startswith: snmpv3
      order: 790
    - lineage:
        - startswith: vsx
      order: 800
    - lineage:
        - startswith: interface 1/1
      order: 810
    - lineage:
        - startswith: ip
      order: 820
    - lineage:
        - startswith: router
      order: 850
    - lineage:
        - startswith: https-server
      order: 900
    - lineage:
        - startswith: nae-script
      order: 950
    - lineage:
        - startswith: nae-agent
      order: 960
  # adds +1 indent to lines following start_expression and removes the +1 indent for lines following end_expression
  indent_adjust: []
  parent_allows_duplicate_child: []
  sectional_exiting:
    # This rule is used in the hierarchical_configuration unit test for .add_section_exiting()
    - lineage:
        - startswith: router bgp
        - startswith: template peer-policy
      exit_text: exit-peer-policy
    - lineage:
        - startswith: router bgp
        - startswith: template peer-session
      exit_text: exit-peer-session
    - lineage:
        - startswith: router bgp
        - startswith: address-family
      exit_text: exit-address-family
  # substitions against the full multi-line config text
  full_text_sub: []
  #- search: 'banner\s(exec|motd)\s(\S)\n(.*\n){1,}(\2)'
  #  replace: ''
  #- search: 'banner\s(exec|motd)\s(\S.).+\n(.*\n){1,}.*(\2)'
  #  replace: ''
  #- search: 'banner\s(exec|motd)\s(\S.)\n(.*\n){1,}(\2)'
  #  replace: ''
  # substitions against each line of the config text
  per_line_sub:
    - search: ^Building configuration.*
      replace: ""
    - search: ^Current configuration.*
      replace: ""
    - search: ^! Last configuration change.*
      replace: ""
    - search: ^! NVRAM config last updated.*
      replace: ""
    - search: ^ntp clock-period .*
      replace: ""
    - search: ^version.*
      replace: ""
    - search: ^ logging event link-status$
      replace: ""
    - search: ^ logging event subif-link-status$
      replace: ""
    - search: ^\s*ipv6 unreachables disable$
      replace: ""
    - search: ^end$
      replace: ""
    - search: '^\s*[#!].*'
      replace: ""
    - search: ^ no ip address
      replace: ""
    - search: ^ exit-peer-policy
      replace: ""
    - search: ^ exit-peer-session
      replace: ""
    - search: ^ exit-address-family
      replace: ""
    - search: ^crypto key generate rsa general-keys.*$
      replace: ""
  idempotent_commands_blacklist: []
  
  # These commands do not require negation, they simply overwrite themselves
  # Example Syntax
  # - lineage:
  #   - startswith: interface
  #   - startswith: description
  idempotent_commands:
    - lineage:
        - startswith: vlan
        - startswith: name
    - lineage:
        - startswith: interface
        - startswith:
            - description
            - ip address
    - lineage:
        - startswith: router ospf 1
        - startswith: router-id
    - lineage:
        - startswith: vsx
        - startswith: system-mac
    - lineage:
        - startswith: vsx
        - startswith: inter-switch-link
    - lineage:
        - startswith: vsx
        - startswith: role
    - lineage:
        - startswith: hostname
  # Default when expression: list of expressions
  negation_default_when: []
  # Negate substitutions: expression -> negate with
  # # Example Syntax:
  # - lineage:
  #   - startswith: vsx
  #   - startswith: description
  #  use: no description
  
  negation_negate_with: 
  - lineage:
    - startswith: vsx
    - startswith: keepalive peer
    use: no keepalive  